djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceApp/',include('ecommerceApp.urls')),
]

djangoProject/ecommerceApp/urls.py
from django.urls import path
from . import views 

app_name = 'ecommerceApp'

urlpatterns = [
        path('', views.home, name='home'),
        path('products/', views.product_list, name='product_list'),
        path('products/<int:pk>/', views.product_details,name='product_details'),
        path('customers/', views.customer_list, name='customer_list'),
        path('customers/<int:pk>/', views.customer_details, name='customer_details'),

        ]

djangoProject/ecommerceApp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='products/')
    availability = models.BooleanField(default=True)


    def __str__(self):
        return self.name

class Customer(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"


# add more fields
# MV(AddUrl link to project url)T

djangoProject/ecommerceApp/views.py
from django.shortcuts import get_object_or_404, render
from . models import Customer, Product

# Create your views here.

def home(request):
    return render(request, 'ecommerceApp/home.html')

def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products
        }
    return render(request,'ecommerceApp/product_list.html',context)

def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
            'product': product
            }
    return render(request, 'ecommerceApp/product_details.html', context)

def customer_list(request):
    customers = Customer.objects.all()
    context = {
            'customers': customers
            }
    return render(request, 'ecommerceApp/customer_list.html', context)

def customer_details(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    context = {
            'customer' : customer

    }
    return render(request, 'ecommerceApp/customer_details.html', context)


    
# Create your views here.

djangoProject/ecommerceApp/templates/ecommerceApp/customer_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Customer List</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
</head>
<body>
  <h1>Customer Details</h1>
    <div class="container">

        <div class="customer-details">
           <h3> {{customer.first_name}}{{ customer.last_name}} </h3>
           <p><strong>Phone: </strong> {{customer.phone}}</p> 
           <p><strong>Address: </strong> {{customer.address}}</p>
           <p><strong>Email: </strong> {{customer.email}}</p>
           <p><strong>Joined on: </strong> {{customer.created_at}}</p>
        </div>
       
        
    </div>
    

</body>
{% comment %} <a href ="{% url 'ecommerceApp:customer_list' %}"> Back to Customer List</a> {% endcomment %}
</html>

djangoProject/ecommerceApp/templates/ecommerceApp/customer_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Customer List</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
</head>
<body>
  <h1>Customer Details</h1>
    <div class="container">

        <div class="customer-details">
           <h3> {{customer.first_name}}{{ customer.last_name}} </h3>
           <p><strong>Phone: </strong> {{customer.phone}}</p> 
           <p><strong>Address: </strong> {{customer.address}}</p>
           <p><strong>Email: </strong> {{customer.email}}</p>
           <p><strong>Joined on: </strong> {{customer.created_at}}</p>
        </div>
       
        
    </div>
    

</body>
{% comment %} <a href ="{% url 'ecommerceApp:customer_list' %}"> Back to Customer List</a> {% endcomment %}
</html>

djangoProject/ecommerceApp/templates/ecommerceApp/customer_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Customer List</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
</head>
<body>
  <h1>Customer List</h1>
  <ul>
    {% for customer in customers %}
      <li>
        <a href="{% url 'ecommerceApp:customer_details' customer.pk %}">
          {{ customer.first_name }} {{ customer.last_name }} {{ customer.email }}
        </a>
      </li>
    {% endfor %}
  </ul>
  
</body>
{% comment %} <a href="{% url 'ecommerceApp:customer_list' %}"> Back to Customer List</a> {% endcomment %}
</html>

djangoProject/ecommerceApp/templates/ecommerceApp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ecommerceApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
</head>
<body>
  <h1>Welcome to Cynthia's E-commerce Website</h1>
  <nav>
    <ul>
      <li><a href="{% url 'ecommerceApp:product_list' %}">Products</a></li>
      <li><a href="{% url 'ecommerceApp:customer_list' %}">Customers</a></li>
    </ul>
  </nav>
</body>

</html>

djangoProject/ecommerceApp/templates/ecommerceApp/product_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{{product.name}}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
</head>
<body>

    
    <ul>
           {% for product in products %}
        <li>
            <h2>{{product.name}} </h2>
            <p>  {{ product.description}}</p>
            <p> Price: Kshs.{{product.price}}</p>
            <img src="{{product.image.url}}" alt="{{product.name}}">
            <p> Available: {{product.available|yesno:"Yes,No"}} </p>
            <a href="{% url 'ecommerceApp:product_list' %}">Back to Product List</a>
        </li>
    {% endfor %}
    
    
</body>
</ul>
{% comment %} <a href ="{% url 'ecommerceApp:product_list' %}"> Back to Product List</a> {% endcomment %}
</html>

djangoProject/ecommerceApp/templates/ecommerceApp/product_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Product List</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="{% static 'ecommerceApp/style.css' %}">
  
</head>
<body>
  <h1>Products</h1>
  <ul> 
{% for product in products%}

 <li>
    <h2>{{product.name}} </h2>
    <p>  {{ product.description}}</p>
    <p> Price: {{product.price}}</p>
    <img src="{{product.image.url}}" alt="{{product.name}}">
    <p><a href="{% url 'ecommerceApp:product_details' product.pk %}">View details</a></p>
  </li>
{% endfor %}
  </ul>
</body>
</html>